### ISSUE TITLE
Add link to presentation

### ISSUE THREAD

**Issue by h-oll** [Preetam/compose-postgresql-grafana#2]
Hi, 

thanks for the repo. I'd suggest adding a link to your presentation at postgresconf: https://postgresconf.org/system/events/document/000/000/964/Visualizing_Data_in_PostgreSQL_With_Grafana.pdf

would make the repo even easier to use.

Cheers

**Comment by Preetam** [comment]
Will do.

**Comment by Preetam** [comment]
Done.
